# Generated by Django 5.1.6 on 2025-02-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reward",
            name="cost",
            field=models.IntegerField(default=0),
        ),
    ]
