# Generated by Django 5.1.6 on 2025-02-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quest",
            name="category",
        ),
        migrations.RemoveField(
            model_name="quest",
            name="status",
        ),
        migrations.AddField(
            model_name="quest",
            name="repeat_type",
            field=models.CharField(
                choices=[
                    ("none", "반복없음"),
                    ("daily", "매일 반복"),
                    ("weekly", "매주 반복"),
                    ("monthly", "매월 반복"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
